apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-haproxy
  namespace: petclinic
  annotations:
    ingress.class: "haproxy"
    haproxy.org/check: "enabled"
    haproxy.org/load-balance: "leastconn"
    haproxy.org/ssl-redirect: "true"
    haproxy.org/rate-limit-requests: "100"
spec:
  ingressClassName: haproxy
  tls:
    - hosts: [petclinic-ha.mycompany.com]
      secretName: petclinic-tls
  rules:
    - host: petclinic-ha.mycompany.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: petclinic
                port:
                  number: 8080
