apiVersion: v1
kind: ServiceAccount
metadata:
  name: petclinic-sa
  namespace: petclinic
  annotations:
    azure.workload.identity/client-id: "<workload-identity-client-id>"
automountServiceAccountToken: false
