apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: petclinic-runtime-visibility
spec:
  kprobes:
    - call: "sys_execve"
      syscall: true
      args:
        - index: 0
          type: "string"
        - index: 1
          type: "string_array"
      selectors:
        - matchNamespaces:
            - operator: In
              values: ["petclinic"]
          matchActions:
            - action: Sigkill
              argError: -1
    - call: "sys_connect"
      syscall: true
      args:
        - index: 0
          type: "int"
        - index: 1
          type: "sockaddr"
      selectors:
        - matchNamespaces:
            - operator: In
              values: ["petclinic"]
          matchActions:
            - action: Post
